name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout my code
      uses: actions/checkout@v3

    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: testacreroltest.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          testacreroltest.azurecr.io/redux/app:latest
          testacreroltest.azurecr.io/redux/app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'testacrapperol'
        publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
        images: 'testacreroltest.azurecr.io/redux/app:latest'
#         images: 'contoso.azurecr.io/nodejssampleapp:${{ github.sha }}'
    
    
